# GCP -> 1 vCPU + 4GB Ram e2-large
# 48.92e per month / 730h = 0.067/h
apiVersion: rating.alterway.fr/v1
kind: ReactiveRule
metadata:
  name: reactive-rule-node-cost-simulation-gcp-e2-large
  namespace: {{ .Release.Namespace }}
spec:
  metric: ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/sum(gcp_e2_large_memory) > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(gcp_e2_large_cpu) or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(gcp_e2_large_cpu)) * sum(gcp_e2_large)
  name: node_cost_simulation_gcp_e2_large
  timeframe: 3600s
---
apiVersion: rating.alterway.fr/v1
kind: ReactiveRule
metadata:
  name: reactive-rule-number-instance-simulation-gcp-e2-large
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / sum(gcp_e2_large_memory)) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(gcp_e2_large_cpu)) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(gcp_e2_large_cpu))
  name: number_instance_simulation_gcp_e2_large
  timeframe: 3600s



# max_over_time(
#   (
#     (
#       ceil(
#         sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)
#       ) / 0.5) > (
#       ceil(
#         sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes) / (1024*1024*1024)
#       ) / 0.75) or (
#       ceil(
#         sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes) / (1024*1024*1024)
#       ) / 0.75) > (
#       ceil(
#         sum(instance:node_filesystem_usage:sum) / (1024*1024*1024)
#       ) / 0.8) or (
#       ceil(
#         sum(instance:node_filesystem_usage:sum) / (1024*1024*1024)
#       ) / 0.8)
#     ) * sum(gcp_e2_large)
# )