# AKS -> 1 vCPU + 1GB Ram b1s 0.0164/h
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModels
metadata:
  name: rating-rule-model-node-cost-simulation-aks-b1s
  namespace: {{ .Release.Namespace }}
spec:
  metric: ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/sum(aks_b1s_memory) > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum))) / sum(aks_b1s_cpu) or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(aks_b1s_cpu)) * sum(aks_b1s)
  name: node_cost_simulation_aks_b1s
  timeframe: 3600s
---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModels
metadata:
  name: rating-rule-model-number-instance-simulation-aks-b1s
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / sum(aks_b1s_memory)) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(aks_b1s_cpu)) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(aks_b1s_cpu))
  name: number_instance_simulation_aks_b1s
  timeframe: 3600s
