# AWS -> 2 vCPU + 8GB Ram m6g.large 0.077/h
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModel
metadata:
  name: rating-rule-model-node-cost-simulation-aws-m6g-large
  namespace: {{ .Release.Namespace }}
spec:
  metric: ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/sum(aws_m6g_large_memory) > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(aws_m6g_large_cpu) or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(aws_m6g_large_cpu)) * sum(aws_m6g_large)
  name: node_cost_simulation_aws_m6g_large
  timeframe: 3600s
---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModel
metadata:
  name: rating-rule-model-number-instance-simulation-aws-m6g-large
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / sum(aws_m6g_large_memory)) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(aws_m6g_large_cpu)) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(aws_m6g_large_cpu))
  name: number_instance_simulation_aws_m6g_large
  timeframe: 3600s