# GCP -> 1 vCPU + 4GB Ram e2-highcpu-2
# 48.92e per month / 730h = 0.067/h
apiVersion: rating.alterway.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-node-cost-simulation-gcp-e2-highcpu-4
  namespace: {{ .Release.Namespace }}
spec:
  metric: ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/{memory} > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum))) / {cpu} or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/{cpu}) * {price}
  name: node_cost_simulation_gcp_e2_highcpu_4
  timeframe: 3600s
  cpu: "1"
  memory: "4"
  price: "0.067"
---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-number-instance-simulation-gcp-e2-highcpu-4
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / {memory}) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / {cpu}) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / {price})
  name: number_instance_simulation_gcp_e2_highcpu_4
  timeframe: 3600s
  cpu: "1"
  memory: "4"
  price: "0.067"
