# AWS -> 1 vCPU + 2GB Ram 0.0255/h
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModels
metadata:
  name: rating-rule-model-node-cost-simulation-aws-a1-medium
  namespace: {{ .Release.Namespace }}
spec:
  metric:  ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/sum(aws_a1_medium_memory) > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(aws_a1_medium_cpu) or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(aws_a1_medium_cpu)) * sum(aws_a1_medium)
  name: node_cost_simulation_aws_a1_medium
  timeframe: 3600s
---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModels
metadata:
  name: rating-rule-model-number-instance-simulation-aws-a1-medium
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / sum(aws_a1_medium_memory)) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(aws_a1_medium_cpu)) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(aws_a1_medium_cpu))
  name: number_instance_simulation_aws_a1_medium
  timeframe: 3600s