apiVersion: rating.smile.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-node-cpu-memory-ratio
  namespace: {{ .Release.Namespace }}
spec:
  metric: sum(instance:node_cpu:ratio) by (instance) / on (instance) group_left sum(instance:node_memory_utilisation:ratio) by (instance)
  name: node_cpu_memory_ratio
  timeframe: 3s
