# GCP -> 1 vCPU + 4GB Ram e2-micro
# 48.92e per month / 730h = 0.067/h
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModel
metadata:
  name: rating-rule-model-node-cost-simulation-gcp-e2-micro
  namespace: {{ .Release.Namespace }}
spec:
  metric: ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/sum(gcp_e2_micro_memory) > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(gcp_e2_micro_cpu) or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/sum(gcp_e2_micro_cpu)) * sum(gcp_e2_micro)
  name: node_cost_simulation_gcp_e2_micro
  timeframe: 3600s
---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleModel
metadata:
  name: rating-rule-model-number-instance-simulation-gcp-e2-micro
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / sum(gcp_e2_micro_memory)) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(gcp_e2_micro_cpu)) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / sum(gcp_e2_micro_cpu))
  name: number_instance_simulation_gcp_e2_micro
  timeframe: 3600s