apiVersion: rating.smile.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-node-cpu-memory-ratio-evolution
  namespace: {{ .Release.Namespace }}
spec:
  metric: (sum(rate(instance:node_cpu:ratio[24h])) by (instance) / on (instance) group_left sum(rate(instance:node_memory_utilisation:ratio[24h])) by (instance))
  name: node_cpu_memory_ratio_evolution
  timeframe: 3s
