# AKS -> 2 vCPU + 8GB Ram b2ms 0.135/h
apiVersion: rating.alterway.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-node-cost-simulation-aks-b2ms
  namespace: {{ .Release.Namespace }}
spec:
  metric: ((ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)))/{memory} > (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum))) / {cpu} or (ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)))/{cpu}) * {price}
  name: node_cost_simulation_aks_b2ms
  timeframe: 3600s
  cpu: "2"
  memory: "8"
  price: "0.135"
---
apiVersion: rating.alterway.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-number-instance-simulation-aks-b2ms
  namespace: {{ .Release.Namespace }}
spec:
  metric: ceil(ceil(sum(instance:node_memory_utilisation:ratio) * max(node_memory_MemTotal_bytes)/(1024*1024*1024)) / {memory}) > ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / {cpu}) or ceil(ceil(sum(instance:node_cpu:ratio) * max(instance:node_num_cpu:sum)) / {price})
  name: number_instance_simulation_aks_b2ms
  timeframe: 3600s
  cpu: "2"
  memory: "8"
  price: "0.135"