apiVersion: rating.smile.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-pod-usage-memory
  namespace: {{ .Release.Namespace }}
spec:
  metric: (usage_memory * on () group_right sum(container_memory_usage_bytes) by (pod, namespace) + on (pod, namespace) group_left(node) (sum(kube_pod_info{pod_ip!="",node!="",host_ip!=""}) by (pod, namespace, node) * 0)) / 10000000000
  name: pods_usage_memory
  timeframe: 3s