apiVersion: rating.smile.fr/v1
kind: RatingRuleInstance
metadata:
  name: rating-rule-instance-prometheus-oldest-data
  namespace: {{ .Release.Namespace }}
spec:
  metric: min(prometheus_tsdb_lowest_timestamp)
  name: prometheus_oldest_data
  timeframe: 3600s