apiVersion: rating.alterway.fr/v1
kind: RatingRuleModels
metadata:
  name: rating-rule-model-prometheus-oldest-data
  namespace: {{ .Release.Namespace }}
spec:
  metric: min(prometheus_tsdb_lowest_timestamp)
  name: prometheus_oldest_data
  timeframe: 3600s