apiVersion: rating.alterway.fr/v1
kind: ReactiveRule
metadata:
  name: reactive-rule-prometheus-oldest-data
  namespace: {{ .Release.Namespace }}
spec:
  metric: min(prometheus_tsdb_lowest_timestamp)
  name: prometheus_oldest_data
  timeframe: 3600s