apiVersion: rating.alterway.fr/v1
kind: RatingRuleModels
metadata:
  name: rating-rule-model-tenant-storage-use
  namespace: {{ .Release.Namespace }}
spec:
  metric: (sum(kubelet_volume_stats_capacity_bytes) by (namespace, node, persistentvolumeclaim) - sum(kubelet_volume_stats_available_bytes) by (namespace, node, persistentvolumeclaim))/(1024*1024*1024)
  name: tenant_storage_use
  timeframe: 3600s
