{
 "title": "Cloud prices dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "GCP Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily e2-highmem-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly e2-highmem-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly e2-highmem_2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date e2-highmem-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_medium\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_large\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_xlarge\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_highmem_2\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_highcpu_2\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_micro\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  { "title": "AWS Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Daily a1-medium ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily a1-large ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily a1-xlarge ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly a1-medium ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly a1-large ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly a1-xlarge ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly a1-medium ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly a1-large ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly a1-xlarge ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date a1-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date a1-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date a1-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_medium\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_large\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_xlarge\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_2_xlarge\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_t4g_micro\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_t4g_nano\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  { "title": "Azure Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Daily b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Daily a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\"}",
     "target": "/metrics/<metric>/daily",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Weekly a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\"}",
     "target": "/metrics/<metric>/weekly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "Monthly a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\"}",
     "target": "/metrics/<metric>/monthly",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "title": "To date a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\"}",
     "target": "/metrics/<metric>/todate",
     "type": "table"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b2s\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b2ms\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b4ms\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b1s\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b1ms\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    },
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_a8\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  }
 ]
}