{
 "title": "Main dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Nodes rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "/nodes/rating", "type": "timeseries" }
   ]
  },
  {
   "title": "Namespaces rating",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 5, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "/namespaces/rating", "type": "timeseries" }
   ]
  },
  {
   "title": "Pods rating",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"usage_cpu\"}",
     "target": "/pods/rating",
     "type": "timeseries"
    }
   ]
  }
 ]
}