{
 "title": "Default dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rating-operator CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"pods_usage_cpu\", \"namespace\": \"rating-operator\"}",
     "target": "/namespaces/<namespace>/metrics/<metric>/rating",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Rating-operator RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"pods_usage_memory\", \"namespace\": \"rating-operator\"}",
     "target": "/namespaces/<namespace>/metrics/<metric>/rating",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Oldest Prometheus data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"prometheus_oldest_data\"}",
     "target": "/metrics/<metric>/rating",
     "type": "table"
    }
   ]
  },
  {
   "title": "Oldest rated data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "/rated/frames/oldest", "type": "table" }
   ]
  },
  {
   "title": "Prometheus storage (GB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"prometheus_storage_size\"}",
     "target": "/metrics/<metric>/rating",
     "type": "table"
    }
   ]
  },
  {
   "title": "Rating storage (GB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"rating_storage_size\"}",
     "target": "/metrics/<metric>/rating",
     "type": "table"
    }
   ]
  },
  {
   "title": "CPU vs RAM on nodes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cpu_memory_ratio\"}",
     "target": "/nodes/metrics/<metric>/rating",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "CPU vs RAM ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"node_cpu_memory_ratio\"}",
     "target": "/metrics/<metric>/rating",
     "type": "table"
    }
   ]
  }
 ]
}