apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-service
  namespace: monitoring
spec:
  selector:
    app: custom-metrics-app  # Matches the label in your Deployment
  ports:
    - protocol: TCP
      port: 8000             # The port on the service
      targetPort: 8000       # The container port to forward traffic to
  type: ClusterIP            # Default service type; restricts access to within the cluster
