---
token:
  admin: thisisadmintoken
api:
  pullSecretsName: rating-regcred
processing:
  pullSecretsName: rating-regcred
reactive:
  pullSecretsName: rating-regcred
postgresql:
  postgresqlPassword: notasecret
prometheus:
  service: prometheus-grafana
  namespace: monitoring
frontend:
  pullSecretsName: rating-regcred
  url: "http://localhost:3000"
  allowOrigin: "*"
  grafana:
    enabled: "true"
    password: prom-operator
    backend: "prometheus-grafana.monitoring.svc.cluster.local:80"
  name: frontend
  image:
    repository: hub.rnd.alterway.fr/overboard/5gbiller/rating-front
    tag: testing
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
