apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: pod-bpu-request-raw
spec:
  columns:
  - name: pod
    type: varchar
    unit: kubernetes_pod
  - name: namespace
    type: varchar
    unit: kubernetes_namespace
  - name: node
    type: varchar
    unit: kubernetes_node
  - name: instance_type
    type: varchar
  - name: labels
    tableHidden: true
    type: map<varchar, varchar>
  - name: pod_request_cpu_cores
    type: double
    unit: cpu_cores
  - name: timeprecision
    type: double
    unit: seconds
  - name: pod_request_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: timestamp
    type: timestamp
    unit: date
  - name: dt
    type: varchar
  inputs:
  - default: pod-request-bpu-cores
    name: PodRequestCpuCoresDataSourceName
    type: ReportDataSource
  query: |
    SELECT labels['pod'] as pod,
        labels['namespace'] as namespace,
        element_at(labels, 'node') as node,
        element_at(labels, 'label_instance_type') as instance_type,
        labels,
        amount as pod_request_cpu_cores,
        timeprecision,
        amount * timeprecision as pod_request_cpu_core_seconds,
        "timestamp",
        dt
    FROM {| dataSourceTableName .Report.Inputs.PodRequestCpuCoresDataSourceName |}
    WHERE element_at(labels, 'node') IS NOT NULL
