---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-admin
  labels:
    {{- include "rating.labels" . | nindent 4 }}

type: Opaque
stringData:
  RATING_ADMIN_API_KEY: {{ .Values.security.token.admin }}
