---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rating.fullname" . }}-admin
  labels:
    {{- include "rating.labels" . | nindent 4 }}

type: Opaque
stringData:
  RATING_ADMIN_API_KEY: {{ .Values.token.admin }}
