---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rating.operator.api.fullname" . }}
  labels:
    app: {{ include "rating.operator.api.fullname" . }}
    app.kubernetes.io/name: {{ include "rating.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    {{- include "rating.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - name: api
    protocol: TCP
    port: {{ .Values.api.service.port }}
    targetPort: 5012
  selector:
    app: {{ include "rating.operator.api.fullname" . }}
    app.kubernetes.io/name: {{ include "rating.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    {{- include "rating.labels" . | nindent 4 }}
