---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rating.fullname" . }}-config-frontend-app
  labels:
    {{- include "rating.labels" . | nindent 4 }}

data:
  env-config.js: |-
    window._env_ = {
      RATING_API_URL: 'api/'
    }
