---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rating.fullname" . }}-config-frontend-proxy
  labels:
    {{- include "rating.labels" . | nindent 4 }}

data:
  {{- (.Files.Glob "files/config/frontend-proxy/*").AsConfig | nindent 2 }}
