{{- if eq .Values.grafana.enabled "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rating.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - name: grafana
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
{{- end}}
