apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  name: prometheus-grafana-out
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30041
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana