---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rating.fullname" . }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "rating.labels" . | nindent 4 }}
