{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rating.fullname" . }}
  labels:
    {{- include "rating.labels" . | nindent 4 }}

rules:
- apiGroups:
  - metering.openshift.io
  resources:
  - reports
  verbs:
  - get
  - watch
  - list
{{- end -}}
