---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rating.fullname" . }}-config-rates-t0
  labels:
    {{- include "rating.labels" . | nindent 4 }}

data:
  {{- (.Files.Glob "files/config/rates/0/*").AsConfig | nindent 2 }}
