---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rating.fullname" . }}-config-rates
spec:
  storageClassName: {{ .Values.api.storage.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
