---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rating.fullname" . }}-{{ .Release.Namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  - pods
  verbs:
  - '*'
- apiGroups:
  - metering.openshift.io
  resources:
  - reports
  verbs:
  - '*'
- apiGroups:
  - rating.alterway.fr
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - ratings
  verbs:
  - '*'
