---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rating.fullname" . }}
  labels:
    {{- include "rating.labels" . | nindent 4 }}

type: Opaque
stringData:
  PRESTO_DATABASE_URI: {{ .Values.metering.presto_database_uri }}
