{
 "title": "[Grafonnet] Default Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Rating-operator", "query": "JSON" }
  ]
 },
 "panels": [
  {
   "title": "Rating-operator CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"pods_usage_cpu\", \"namespace\": \"rating-operator\"}",
     "target": "/namespaces/<namespace>/metrics/<metric>/rating",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Rating-operator RAM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"pods_usage_memory\", \"namespace\": \"rating-operator\"}",
     "target": "/namespaces/<namespace>/metrics/<metric>/rating",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "Oldest Prometheus data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"prometheus_oldest_data\"}",
     "target": "/metrics/<metric>/rating",
     "type": "table"
    }
   ]
  },
  {
   "title": "Oldest rated data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "/rated/frames/oldest", "type": "table" }
   ]
  },
  {
   "title": "Prometheus storage (GB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"prometheus_storage_size\"}",
     "target": "/metrics/<metric>/ratio",
     "type": "table"
    }
   ]
  },
  {
   "title": "Rating storage (GB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"rating_storage_size\"}",
     "target": "/metrics/<metric>/ratio",
     "type": "table"
    }
   ]
  }
 ]
}
{
 "title": "[Grafonnet] Application Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Rating-operator", "query": "JSON" }
  ]
 },
 "panels": [
  {
   "title": "CPU vs RAM ratio per instance (more than 1, CPU is preferred)",
   "type": "gauge",
   "description": "(more than 1, CPU is preferred)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cpu_memory_ratio\"}",
     "target": "/nodes/metrics/<metric>/rating",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "CPU vs RAM ratio (more than 1, CPU is preferred)",
   "type": "graph",
   "description": "(more than 1, CPU is preferred)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"node_cpu_memory_ratio\"}",
     "target": "/metrics/<metric>/ratio",
     "type": "table"
    }
   ]
  },
  {
   "title": "STORAGE vs RAM ratio (more than 1, STORAGE is preferred)",
   "type": "graph",
   "description": "(more than 1, STORAGE is preferred)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "data": "{\"metric\": \"storage_ram_ratio\"}",
     "target": "/metrics/<metric>/ratio",
     "type": "table"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "graph",
   "description": "RAM in GB, CPU in milicore",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "/metrics/rating", "type": "timeseries" }
   ]
  }
 ]
}
{
 "title": "[Grafonnet] Cloud Cost Simulation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Rating-operator", "query": "JSON" }
  ]
 },
 "panels": [
  { "title": "GCP Biling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "title": "AWS Biling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "Azure Biling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "daily e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly e2-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_medium\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly e2-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_large\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly e2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_xlarge\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily e2-highmem-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly e2-highmem-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly e2-highmem-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highmem_2\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly e2-highcpu-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_highcpu_4\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly e2-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_gcp_e2_micro\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily a1-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly a1-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly a1-medium",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_medium\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily a1-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly a1-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly a1-large",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_large\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily a1-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly a1-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly a1-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_xlarge\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly a1-2-xlarge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_a1_2_xlarge\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly t4g-micro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_micro\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly t4g-nano",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aws_t4g_nano\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly b2s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2s\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly b2ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b2ms\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly b4ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b4ms\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly b1s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1s\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly b1ms",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_b1ms\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "daily a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\", \"aggregator\": \"daily\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "weekly a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\", \"aggregator\": \"weekly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "monthly a8",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"node_cost_simulation_aks_a8\", \"aggregator\": \"monthly\"}",
     "target": "/metrics/<metric>/<aggregator>",
     "type": "table"
    }
   ]
  },
  {
   "title": "a1-medium instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_medium\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "a1-large instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_large\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "a1-xlarge instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_xlarge\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "a1-2-xlarge instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_a1_2_xlarge\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "t4g-micro instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_t4g_micro\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "t4g-nano instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aws_t4g_nano\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "e2-medium instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_medium\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "e2-large instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_large\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "e2-xlarge instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_xlarge\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "e2-highmem-2 instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_highmem_2\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "e2-highcpu-4 instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_highcpu_4\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "e2-micro instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_gcp_e2_micro\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "b2s instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b2s\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "b2ms instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b2ms\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "b4ms instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b4ms\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "b1s instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b1s\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "b1ms instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_b1ms\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  },
  {
   "title": "a8 instance needed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"metric\": \"number_instance_simulation_aks_a8\"}",
     "target": "/metrics/<metric>/max",
     "type": "table"
    }
   ]
  }
 ]
}