---
metrics:
  request_cpu:
    report_name: pod-rating-cpu-request-hourly
    presto_table: report_metering_pod_rating_cpu_request_hourly
    presto_column: pod_request_cpu_core_seconds
    unit: core-seconds
  usage_cpu:  
    report_name: pod-rating-cpu-usage-hourly
    presto_table: report_metering_pod_rating_cpu_usage_hourly
    presto_column: pod_usage_cpu_core_seconds
    unit: core-seconds
  request_memory:
    report_name: pod-rating-memory-request-hourly
    presto_table: report_metering_pod_rating_memory_request_hourly
    presto_column: pod_request_memory_byte_seconds
    unit: byte-seconds
  usage_memory:
    report_name: pod-rating-memory-usage-hourly
    presto_table: report_metering_pod_rating_memory_usage_hourly
    presto_column: pod_usage_memory_byte_seconds
    unit: byte-seconds
