---
rules:
-
  name: rules_default
  ruleset:
  -
    metric: request_cpu
    price: 0.5
    unit: core-hours
  -
    metric: usage_cpu
    price: 0.8
    unit: core-hours
  -
    metric: request_memory
    price: 0.0000000001
    unit: GiB-hours
  -
    metric: usage_memory
    price: 0.00000000001
    unit: GiB-hours
