#!/bin/bash

set -eu
set -o pipefail

PROMETHEUS_NAMESPACE=${PROMETHEUS_NAMESPACE:-monitoring}

pwd=$(kubectl get -n "$PROMETHEUS_NAMESPACE" secret prometheus-grafana -o jsonpath="{.data.admin-password}" | base64 --decode)
echo "password: admin / $pwd"

podname=$(kubectl -n "$PROMETHEUS_NAMESPACE" get pods -l app.kubernetes.io/name=grafana -o name | cut -d/ -f2 | head -1)
kubectl -n "$PROMETHEUS_NAMESPACE" port-forward "$podname" 3000:3000
