#!/bin/bash

set -eu
set -o pipefail

METERING_NAMESPACE=${METERING_NAMESPACE:-metering}

podname=$(kubectl -n "$METERING_NAMESPACE" get pods -l app=presto -o name | cut -d/ -f2 | head -1)
kubectl -n "$METERING_NAMESPACE" port-forward "$podname" 8080:8080
