#!/bin/bash

set -eu
set -o pipefail

PROMETHEUS_NAMESPACE=${PROMETHEUS_NAMESPACE:-monitoring}

podname=$(kubectl -n "$PROMETHEUS_NAMESPACE" get pods -l app=alertmanager -o name | cut -d/ -f2 | head -1)
kubectl -n "$PROMETHEUS_NAMESPACE" port-forward "$podname" 9093:9093
