#!/bin/bash

set -eu
set -o pipefail

# forward the nginx sidecar. api is at localhost:8080/api/

podname=$(kubectl get pods -l app.kubernetes.io/name=rating,app.kubernetes.io/component=api -o name | cut -d/ -f2 | head -1)
kubectl port-forward "$podname" 5012:5012 --v=10
