#!/bin/bash

set -eu
set -o pipefail

METERING_NAMESPACE=${METERING_NAMESPACE:-metering}

PODNAME=$(kubectl get pods -n "$METERING_NAMESPACE" -l app=hive,hive=server -o name | cut -d/ -f2)
kubectl -n "$METERING_NAMESPACE" exec -it "$PODNAME" -c hiveserver2 -- beeline -u 'jdbc:hive2://127.0.0.1:10000/metering;auth=noSasl'
