#!/bin/bash

set -eu
set -o pipefail

METERING_NAMESPACE=${METERING_NAMESPACE:-metering}

PODNAME=$(kubectl get pods -n "$METERING_NAMESPACE" -l app=presto,presto=coordinator -o name | cut -d/ -f2)
kubectl -n "$METERING_NAMESPACE" exec -it "$PODNAME" -- /usr/local/bin/presto-cli --server http://presto:8080 --catalog hive --schema metering --user root
# kubectl -n "$METERING_NAMESPACE" exec -it "$PODNAME" -- /usr/local/bin/presto-cli --server http://presto:8080 --catalog hive --schema metering --user root --keystore-path /opt/presto/tls/keystore.pem
