#!/bin/bash

set -eu
set -o pipefail

RATING_NAMESPACE=${RATING_NAMESPACE:-rating}

POSTGRES_PASSWORD=$(kubectl -n "${RATING_NAMESPACE}" get secrets -l app=postgresql -o yaml | grep postgresql-password | cut -d: -f2 | tr -d ' ' | base64 --decode)
# echo "password: $POSTGRES_PASSWORD"

podname=$(kubectl -n "${RATING_NAMESPACE}" get pods -l app=postgresql -o name | cut -d/ -f2 | head -1)
kubectl -n "${RATING_NAMESPACE}" exec -ti "$podname" -- env "PGPASSWORD=${POSTGRES_PASSWORD}" /opt/bitnami/postgresql/bin/psql postgres postgres "$@"
