apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rating-operator
  template:
    metadata:
      labels:
        name: rating-operator
    spec:
      imagePullSecrets:
        - name: rating-regcred
      serviceAccountName: rating-operator
      containers:
        - name: rating-operator
          resources: {}
          image: hub.rnd.alterway.fr/overboard/5gbiller/rating-operator:vdaviot-redirect
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rating-operator"
            - name: PULLSECRETS_API
              value: rating-regcred
            - name: PULLSECRETS_PROCESSING
              value: rating-regcred
            - name: PULLSECRETS_FRONTEND
              value: rating-regcred-front
            - name: POSTGRESQL_PASSWORD
              value: notasecret
            - name: RATING_ADMIN_API_KEY
              value: thisisadmintoken
            - name: GRAFANA
              value: "true"
            - name: GRAFANA_ADMIN_PASSWORD
              value: admin
            - name: GRAFANA_BACKEND_URL
              value: "prometheus-grafana.monitoring.svc.cluster.local:80"
            - name: FRONTEND_URL
              value: "http://localhost:3000"
            - name: ALLOW_ORIGIN
              value: "http://localhost:8080"
