apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rating-operator
  template:
    metadata:
      labels:
        name: rating-operator
    spec:
      serviceAccountName: rating-operator
      containers:
        - name: rating-operator
          # Replace this with the built image name
          image: vdaviot/rating-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rating-operator"
