apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rating-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  - events
  - pods
  - persistentvolumeclaims
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
- apiGroups:
  - authorization.openshift.io
  resources:
  - roles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - rating-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rating.alterway.fr
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rating.smile.fr
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
