apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rating-operator-api
spec:
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: rating-operator-api
    weight: 100
  wildcardPolicy: None