apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rating-manager-binding
subjects:
  - kind: ServiceAccount
    name: rating-rating
    namespace: rating
roleRef:
  kind: ClusterRole
  name: rating-manager-role
  apiGroup: rbac.authorization.k8s.io
