apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rating
  name: rating-role
rules:
- apiGroups: ["rating.smile.fr"]
  resources: ["ratingruleinstances", "ratingruletemplates", "ratedmetrics", "ratingrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
