apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rating-rolebinding
  namespace: rating
subjects:
- kind: ServiceAccount
  name: rating-rating
  namespace: rating
roleRef:
  kind: Role
  name: rating-role
  apiGroup: rbac.authorization.k8s.io
