token:
  admin: thisisadmintoken
api:
  affinity: {}
  config:
    postgres_hostname: '{{ .Release.Name }}-postgresql-headless'
    postgres_secret: '{{ .Release.Name }}-postgresql'
  image:
    pullPolicy: Always
    repository: hub.rnd.alterway.fr/overboard/5gbiller/rating-api
    tag: master
  name: api
  nodeSelector: {}
  resources: {}
  service:
    port: 80
    type: ClusterIP
  storage:
    config:
      storageClass: null
  tolerations: []
fullnameOverride: null
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
metering:
  presto_database_uri: presto://root@presto.metering:8080/hive/metering
nameOverride: null
networkPolicy:
  enabled: false
postgresql:
  enabled: true
processing:
  affinity: {}
  config:
    postgres_hostname: '{{ .Release.Name }}-postgresql-headless'
    postgres_secret: '{{ .Release.Name }}-postgresql'
  image:
    pullPolicy: Always
    repository: hub.rnd.alterway.fr/overboard/5gbiller/processing-operator
    tag: master
  name: processing
  nodeSelector: {}
  resources: {}
  tolerations: []
rbac:
  create: true
service:
  port: 80
  type: ClusterIP
