apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ratedmetrics.rating.alterway.fr
spec:
  scope: Namespaced
  group: rating.alterway.fr
  names:
    kind: RatedMetric
    plural: ratedmetrics
    singular: ratedmetric
    shortNames:
      - rm
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            metric:
              type: string
            date:
              type: string