# RatingRuleModels configures metric to be rated by the rating-operator-engine.
# It contains a promQL expression, aswell as a timeframe and a metric name.
# Through this resource, you can exploit variables declared in the RatingRules
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ratingrulemodels.rating.alterway.fr
spec:
  scope: Namespaced
  group: rating.alterway.fr
  names:
    kind: RatingRuleModel
    plural: ratingrulemodels
    singular: ratingrulemodel
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            timeframe:
              type: string
            metric:
              type: string
