# RatingRules is an object that does two main things:
# 1/ (Deprecated) Holding the reports configuration for metering-operator based rating.
# 2/ Holding the values to use in the rating. Those values can be considered as variables, and will be available in prometheus (exposed by the rating-operator-api)
# Those values can be separated in different rulesets (as an ordered list), and holds labels.
# For any rating action, the operator will try to match each ruleset, labels and metrics to find the one to use.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ratingrules.rating.alterway.fr
spec:
  scope: Namespaced
  group: rating.alterway.fr
  names:
    kind: RatingRule
    plural: ratingrules
    singular: ratingrule
    shortNames:
      - rr
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            valid_from:
              type: string
            rules:
              type: array
              items:
                type: object
            metrics:
              type: object
