apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ratingrules.rating.alterway.fr
spec:
  scope: Namespaced
  group: rating.alterway.fr
  names:
    kind: RatingRule
    plural: ratingrules
    singular: ratingrule
    shortNames:
      - rr
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            valid_from:
              type: string
            rules:
              type: array
              items:
                type: object
            metrics:
              type: object
