apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ratingruletemplates.rating.alterway.fr
spec:
  scope: Namespaced
  group: rating.alterway.fr
  names:
    kind: RatingRuleTemplate
    plural: ratingruletemplates
    singular: ratingruletemplate
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                query_group:
                  type: string
                query_name:
                  type: string
                query_template:
                  type: string