apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  name: pod-request-bpu-cores
spec:
  prometheusMetricsImporter:
    query: |
      sum(kube_pod_container_resource_requests_cpu_cores) by (pod, namespace, node) + on (node) group_left(label_instance_type) (sum(kube_node_labels) by (node,label_instance_type) * 0)
